version: "3"

networks:
  app-net:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "33600:3306"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysql -uroot --database=default --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 4
    networks:
      - app-net

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - .:/var/www/html:ro
    depends_on:
      - php
    networks:
      - app-net

  php:
    container_name: php
    build: .
    volumes:
      - .:/var/www/html:z
    networks:
      - app-net